doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '16.0.0'
                schema_filter: '~^(?!auth\.|extensions\.|storage\.|realtime\.|graphql\.)~'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
                mapping_types:
                    _text: text
                    _int4: integer
                    _int8: bigint
                    code_challenge_method: string
                    factor_status: string
                    factor_type: string
                    jsonb: json
                    vector: json
            maintenance:
                url: '%env(resolve:SESSION_URL)%'
                server_version: '16.0.0'
                schema_filter: '~^(?!auth\.|extensions\.|storage\.|realtime\.|graphql\.)~'
                mapping_types:
                    _text: text
                    _int4: integer
                    _int8: bigint
                    code_challenge_method: string
                    factor_status: string
                    factor_type: string
                    jsonb: json
                    vector: json
    orm:
        auto_generate_proxy_classes: true
        controller_resolver:
            auto_mapping: false
        enable_lazy_ghost_objects: true
        entity_managers:
            default:
                auto_mapping: true
                filters:
                    tenant:
                        class: App\Doctrine\TenantFilter
                        enabled: false
                identity_generation_preferences:
                    Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                report_fields_where_declared: true
                validate_xml_mapping: true

when@test:
    doctrine:
        dbal:
            connections:
                default:
                    url: '%env(resolve:TEST_DATABASE_URL)%'
                    use_savepoints: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
