framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Monitoring\Application\Command\CheckMonitorCommand': async
            'App\Monitor\Domain\Event\IncidentCreatedEvent': async
            'App\Monitor\Domain\Event\IncidentResolvedEvent': async
