when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            enabled: true
            collect: true
            dsn: 'file:%kernel.cache_dir%/profiler'

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            collect: false
