<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260519173355 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE health_checks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, monitor_id INT NOT NULL, status_code SMALLINT NOT NULL, response_time_ms INT NOT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_success BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E466E8FC4CE1C902D77FEDA0 ON health_checks (monitor_id, checked_at)');
        $this->addSql('CREATE TABLE monitors (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, frequency INT NOT NULL, expected_status_code INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, next_check_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_863DAD3D9033212A ON monitors (tenant_id)');
        $this->addSql('CREATE INDEX IDX_863DAD3D9DE753651B5771DD ON monitors (next_check_at, is_active)');
        $this->addSql('ALTER TABLE monitors ADD CONSTRAINT FK_863DAD3D9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE monitor DROP CONSTRAINT fk_e11599859033212a');
        $this->addSql('DROP TABLE monitor');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('CREATE TABLE monitor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, frequency INT NOT NULL, expected_status_code INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_e11599859033212a ON monitor (tenant_id)');
        $this->addSql('ALTER TABLE monitor ADD CONSTRAINT fk_e11599859033212a FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monitors DROP CONSTRAINT FK_863DAD3D9033212A');
        $this->addSql('DROP TABLE health_checks');
        $this->addSql('DROP TABLE monitors');
    }
}
