<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260427153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create tenant and user tables with tenant-scoped relation.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, subdomain VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tenant_subdomain ON tenant (subdomain)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id INT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_identifier_user_tenant_id ON "user" (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_tenant_email ON "user" (tenant_id, email)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_user_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_user_tenant');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE tenant');
    }
}
