# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

tenancy_controllers:
    resource: 
        path: ../src/Tenancy/Infrastructure/Controller/
        namespace: App\Tenancy\Infrastructure\Controller
    type: attribute

identity_controllers:
    resource: 
        path: ../src/Identity/Infrastructure/Controller/
        namespace: App\Identity\Infrastructure\Controller
    type: attribute

api_register:
    path: /api/register
    controller: App\Tenancy\Infrastructure\Controller\RegistrationController::__invoke
    methods: [POST]

api_login_check:
    path: /api/login_check
    methods: [POST]
