services:
    App\Tenant\TenantContext:
        public: true    
    App\Controller\RegistrationController:
        public: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $tenantContext: '@App\Tenant\TenantContext'
            $userRepository: '@App\Repository\UserRepository'
            $passwordHasher: '@security.user_password_hasher'
        tags: ['controller.service_arguments']
    Doctrine\ORM\EntityManagerInterface:
        alias: doctrine.orm.entity_manager
        public: true
    App\EventListener\TenantListener:
        autowire: true
        autoconfigure: true
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
