services:
    App\Tenant\TenantContext:
        public: true    
    App\Controller\RegistrationController:
        public: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $tenantRepository: '@App\Repository\TenantRepository'
            $passwordHasher: '@security.user_password_hasher'
        tags: ['controller.service_arguments']
        bind:
            array $reservedSubdomains: '%app.reserved_subdomains%'
    Doctrine\ORM\EntityManagerInterface:
        alias: doctrine.orm.entity_manager
        public: true
    App\EventListener\TenantListener:
        autowire: true
        autoconfigure: true
        public: true
